<?php

	$title = 'Add new review';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

	if ($user = $this->identity()) {
		
		$userId = $this->escapeHtml($user->getId());
	
	} else {
		throw 'Not logged in';
	}


	$form->setAttribute('action', $this->url('review', array('action' => 'add')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('itemid')->setValue($place->id));
	echo $this->formHidden($form->get('categoryid')->setValue($category));
	echo $this->formHidden($form->get('reviewedby')->setValue($userId));

?>

<div class="modal-body">
<div id="postReview">
	<h1> Post review </h1>
	<?php echo  $this->formReview($form->get('rating')); ?>
</div>
          
<?php echo $this->formTextarea($form->get('comments')); ?>
   
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-success btn-lg"><i class="fa fa-check fa-2x"></i><?php echo $this->formSubmit($form->get('submit')); ?></button>
    <button type="button" class="btn btn-danger btn-lg" data-dismiss="modal"><i class="fa fa-times fa-2x"></i><?php echo $this->translate(' CANCEL')?></button>
</div>

<?php echo $this->form()->closeTag(); ?> 
<?php
