<?php

$title = 'Users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
   
</p>
  
<table class="table">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->getId());?></td>
    <td><?php echo $this->escapeHtml($user->getFirstName());?></td>
    <td>
        
    </td>
</tr>
<?php endforeach; ?>
</table>