<div class="row">

  <?php
// module/Stadium/view/stadium/stadium/index.phtml:

  $title = 'Stadiums';
  $this->headTitle($title);
  ?>
  <h1><?php echo $this->escapeHtml($title); ?></h1>
  <p>
    <a href="<?php echo $this->url('stadium', array('action'=>'add'));?>">Add new stadium</a>
  </p>


  <?php foreach ($stadiums as $stadium) : ?>

  <div class="col-md-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading" style="background-image: linear-gradient(to bottom, #a70050 0px, #a70050 100%);">
        <h3 class="panel-title"><?php echo $this->escapeHtml($stadium->title);?></h3>
      </div>

      <div class="panel-body">

        <!-- ADMIN OPTIONS -->
    <!--    <a href="<?php echo $this->url('stadium',
        array('action'=>'edit', 'id' => $stadium->id));?>"><i class="fa fa-edit fa-2x"></i></a>
        <a href="<?php echo $this->url('stadium',
        array('action'=>'delete', 'id' => $stadium->id));?>"><i class="fa fa-times fa-2x"></i></a>
        <!-- END ADMIN OPTIONS -->

<p><a href="<?php echo $this->url('stadium', array('action'=>'item', 'id' => $stadium->id));?>"><img class="imageBox" src="<?php echo $this->basePath('img/stadium/'.$stadium->id.'.png') ?>" alt="<?php echo $stadium->title ?>"/></a></p>


<!-- COUNT OF REVIEWS -->
<!--  <?php foreach ($reviews as $review) : ?>
	$count = 0;
  <?php  
  if( ($this->escapeHtml($review->itemid) == $this->escapeHtml($stadium->id) ))
  {
  	$count++;
  }
   endforeach;
?>
<!-- END COUNT OF REVIEWS -->

<center>
Reviews:<span class="badge"><?php echo $this->escapeHtml($stadium->id); ?></span><br/>
Rating:
<i class="fa fa-thumbs-up fa-1x" style="color: #70d900;"></i>
<i class="fa fa-thumbs-up fa-1x" style="color: #70d900;"></i>
<i class="fa fa-thumbs-up fa-1x" style="color: #70d900;"></i>
<i class="fa fa-thumbs-down fa-1x" style="color: #d9534f;"></i>
<i class="fa fa-thumbs-down fa-1x" style="color: #d9534f;"></i>
</center>

</div>
</div>
</div>

<?php endforeach; ?>



</div>