<div class="row">
  
  <?php
// module/Stadium/view/stadium/stadium/index.phtml:

  $title = 'Stadiums';
  $this->headTitle($title);
  ?>
  <h1><?php echo $this->escapeHtml($title); ?></h1>
  <p>
    <a href="<?php echo $this->url('stadium', array('action'=>'add'));?>">Add new stadium</a>
  </p>


  <?php foreach ($stadiums as $stadium) : ?>

  <div class="col-md-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading" style="background-image: linear-gradient(to bottom, #b5b2b4 0px, #b5b2b4 100%);">
        <h3 class="panel-title"><?php echo $this->escapeHtml($stadium->title);?></h3>
      </div>

      <div class="panel-body">

       <p><a href="<?php echo $this->url('stadium', array('action'=>'item', 'id' => $stadium->id));?>"><img class="imageBox" src="<?php echo $this->basePath('img/stadium/'.$stadium->id.'.png') ?>" alt="<?php echo $stadium->title ?>"/></a></p>


       <a href="<?php echo $this->url('stadium',
       array('action'=>'edit', 'id' => $stadium->id));?>"><i class="fa fa-edit fa-2x"></i></a>
<a href="<?php echo $this->url('stadium',
array('action'=>'delete', 'id' => $stadium->id));?>"><i class="fa fa-times fa-2x"></i></a>

<a href="#">Reviewedby: <span class="badge">42</span></a>

</div>
</div>
</div>

<?php endforeach; ?>



</div>
