<?php
// module/Stadium/view/stadium/stadium/index.phtml:

$title = 'My stadiums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('stadium', array('action'=>'add'));?>">Add new stadium</a>
</p>


















<?php foreach ($stadiums as $stadium) : ?>

    <?php echo $this->escapeHtml($stadium->title);?>

    <?php echo $this->escapeHtml($stadium->address);?>

        <a href="<?php echo $this->url('stadium',
            array('action'=>'edit', 'id' => $stadium->id));?>">Edit</a>
        <a href="<?php echo $this->url('stadium',
            array('action'=>'delete', 'id' => $stadium->id));?>">Delete</a>


<?php endforeach; ?>

