<div class="row">
  
<?php
// module/Stadium/view/stadium/stadium/index.phtml:

$title = 'Stadiums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('stadium', array('action'=>'add'));?>">Add new stadium</a>
</p>


<?php foreach ($stadiums as $stadium) : ?>

    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #b5b2b4 0px, #b5b2b4 100%);">
                <h3 class="panel-title"><?php echo $this->escapeHtml($stadium->title);?></h3>
            </div>

			<div class="panel-body">
                 <p><img class="imageBox" src="<?php echo $this->basePath('img/stadium/'.$stadium->id.'.png') ?>" alt="Stadium" data-toggle="modal" data-target="#modalInfo<?php echo $this->escapeHtml($stadium->id);?>" /></p>


        <a href="<?php echo $this->url('stadium',
            array('action'=>'edit', 'id' => $stadium->id));?>"><i class="fa fa-edit fa-2x"></i></a>
        <a href="<?php echo $this->url('stadium',
            array('action'=>'delete', 'id' => $stadium->id));?>"><i class="fa fa-times fa-2x"></i></a>




<!-- Button trigger modal REVIEW -->
<button class="btn btn-primary" data-toggle="modal" data-target="#modalReview<?php echo $this->escapeHtml($stadium->id);?>">
  <i class="fa fa-pencil fa-1x"></i> Reviews
</button>



<!-- Modal INFO -->
<div class="modal fade bs-example-modal-lg" id="modalInfo<?php echo $this->escapeHtml($stadium->id);?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->escapeHtml($stadium->title);?></h4>
      </div>
      <div class="modal-body">


      <h1> <?php echo $this->escapeHtml($stadium->title);?> </h1>

      <img src="<?php echo $this->basePath('img/stadium/'.$stadium->id.'.png') ?>" alt="<?php echo $this->escapeHtml($stadium->title);?>" />

      <h3> <?php echo $this->escapeHtml($stadium->address);?> </h3>

      <?php echo $this->escapeHtml($stadium->info);?>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- END Modal INFO -->


<!-- Modal REVIEW -->
<div class="modal fade bs-example-modal-lg" id="modalReview<?php echo $this->escapeHtml($stadium->id);?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->escapeHtml($stadium->title);?></h4>
      </div>
      <div class="modal-body">


      <h1> <?php echo $this->escapeHtml($stadium->title);?> </h1>

      <h2> Post review </h2>


<!-- RATING -->
<div class="star-rating"> 
  <span class="fa fa-thumbs-o-up fa-3x" data-rating="1"></span>
  <span class="fa fa-thumbs-o-up fa-3x" data-rating="2"></span>
  <span class="fa fa-thumbs-o-up fa-3x" data-rating="3"></span>
  <span class="fa fa-thumbs-o-up fa-3x" data-rating="4"></span>
  <span class="fa fa-thumbs-o-up fa-3x" data-rating="5"></span>
  <input type="hidden" name="whatever" class="rating-value" value="3">
</div>

<!-- END RATING -->

      <textarea class="form-control" rows="3"></textarea>





<!-- REVIEW INN271 -->
  <form method="POST">


    <h1> Post Review </h1>

    <font size="5">Select rating:</font>
    <!-- Drop down menu to select Geolocation or Suburb -->
    <select id="ratingDd" name="ratingDd">
      <option value="0"></option>
      <option value="1">&#9733;&#9734;&#9734;&#9734;&#9734;</option>
      <option value="2">&#9733;&#9733;&#9734;&#9734;&#9734;</option>
      <option value="3">&#9733;&#9733;&#9733;&#9734;&#9734;</option>
      <option value="4">&#9733;&#9733;&#9733;&#9733;&#9734;</option>
      <option value="5">&#9733;&#9733;&#9733;&#9733;&#9733;</option>
    </select>

    <p>
      <textarea name="reviewTa" id="reviewTa" autofocus placeholder="Write a review..."></textarea>
    </p>


    <?php

      if(isset($_POST["submitReviewBtn<?php echo $this->escapeHtml($stadium->id);?>"]))
      {

    //    $sessionid = session_id();

        $itemid = 1;

        $rating = $_POST['ratingDd'];
        $comments = $_POST['reviewTa'];
    //    $reviewedby = getUserId($sessionId);
        $reviewedby = 2;
        $date = date('Y-m-d H:i:s');


        postReview($itemid, $rating, $comments, $reviewedby, $date);

      }
    ?>

    <input id="submitReviewBtn<?php echo $this->escapeHtml($stadium->id);?>" name="submitReviewBtn<?php echo $this->escapeHtml($stadium->id);?>" type="submit" value="Submit"/>


  </form>

<!-- END REVIEW INN271 -->











      <h2> Reviews </h2>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- END Modal REVIEW -->





            </div>
        </div>
   </div>
   



<?php endforeach; ?>


<?php 
  function postReview($itemid, $rating, $comments, $reviewedby, $date)
  {
        try  
    { 
      $stmt = $pdo->prepare(

      'INSERT INTO review (itemid, rating, comments, reviewedby, reviewdate)
      VALUES (:revieweditemid, :rating, :comments, :reviewedby, :reviewdate)'
      ); 

      $stmt->bindValue(':itemid', $itemid);
      $stmt->bindValue(':rating', $rating);
      $stmt->bindValue(':comments', $comments);
      $stmt->bindValue(':reviewedby', $reviewedby);
      $stmt->bindValue(':reviewdate', $date);

      $stmt->execute();

    }
    catch (PDOException $e) 
    { 
      echo $e->getMessage(); 
    }
    echo "!!!";
  }




?>


 </div>
