<div class="jumbotron">

	<a class="btn btn-success btn-lg pull-left" href="./../" ><i class="fa fa-arrow-left fa-2x"></i><?php echo $this->translate(' BACK')?></a>
	<br/>


	<?php
	$title = $this->escapeHtml($stadium->title);
	$this->headTitle($title);
	?>
	<h1><?php echo $this->escapeHtml($title); ?></h1>


  <img src="<?php echo $this->basePath('img/stadium/'.$stadium->id.'.png') ?>" alt="<?php echo $this->escapeHtml($stadium->title);?>" />
  <br/>

  <?php echo $this->escapeHtml($stadium->address);?>
  <br/>
  <?php echo $this->escapeHtml($stadium->telephone);?>
  <br/>

  <?php 

  $email = $this->escapeHtml($stadium->email);

  if($email != '')
  {
    echo $email.'<br/>';
  }

  ?>

  
  <?php echo $this->escapeHtml($stadium->website);?>
  <br/>


  <?php echo $this->escapeHtml($stadium->info);?>
  <br/>






  <h2>User reviews:</h2>
  <!-- Button trigger modal REVIEW -->
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modalReview<?php echo $this->escapeHtml($stadium->id);?>">
    <i class="fa fa-pencil fa-2x"></i> Post Review
  </button>
  <br/>




  <!-- Modal REVIEW -->
  <div class="modal fade bs-example-modal-lg" id="modalReview<?php echo $this->escapeHtml($stadium->id);?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel"><?php echo $this->escapeHtml($stadium->title);?></h4>
        </div>
        <div class="modal-body">

          <h1> Post review </h1>



          <!-- RATING -->
<!--          <?php
          $up = 5;
          $down = 5 - $up;

          for ($t=$up; $t>0; $t--) 
          {
            echo "<input type='radio' name=$up value=$up>";

            for ($i=$up; $i>0; $i--) 
            {
              echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
            }
            echo '<br>';
            $up=$up-1;
          }
          ?>
-->



          <input type="radio" name="5" value="5">
          <?php for ($i=1; $i<=5; $i++) 
          {
            echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
          }
          echo ' <b>Very Good</b><br>';
          ?>

          <input type="radio" name="4" value="4">
          <?php 
          for ($i=1; $i<=4; $i++) 
          {
            echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
          }
          for ($i=1; $i<=1; $i++) 
          {
            echo '<i class="fa fa-thumbs-down fa-2x" style="color: #d9534f;"></i>';
          }
          echo ' <b>Good</b><br>';
          ?>

          <input type="radio" name="3" value="3">
          <?php 
          for ($i=1; $i<=3; $i++) 
          {
            echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
          }
          for ($i=1; $i<=2; $i++) 
          {
            echo '<i class="fa fa-thumbs-down fa-2x" style="color: #d9534f;"></i>';
          }
          echo ' <b>Satisfactory</b><br>';
          ?>

          <input type="radio" name="2" value="2">
          <?php 
          for ($i=1; $i<=2; $i++) 
          {
            echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
          }
          for ($i=1; $i<=3; $i++) 
          {
            echo '<i class="fa fa-thumbs-down fa-2x" style="color: #d9534f;"></i>';
          }
          echo ' <b>Bad</b><br>';
          ?>

          <input type="radio" name="1" value="1">
          <?php 
          for ($i=1; $i<=1; $i++) 
          {
            echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
          }
          for ($i=1; $i<=4; $i++) 
          {
            echo '<i class="fa fa-thumbs-down fa-2x" style="color: #d9534f;"></i>';
          }
          echo ' <b>Very Bad</b>';
          ?>
          <br/>
          <br/>



          <!-- END RATING -->

          <textarea class="form-control" rows="5" autofocus placeholder="Write comments..."></textarea>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success btn-lg"><i class="fa fa-check fa-2x"></i><?php echo $this->translate(' POST')?></button>
          <button type="button" class="btn btn-danger btn-lg" data-dismiss="modal"><i class="fa fa-times fa-2x"></i><?php echo $this->translate(' CANCEL')?></button>

        </div>
      </div>
    </div>
  </div>
  <!-- END Modal REVIEW -->

  <?php /*
  function postReview($itemid, $rating, $comments, $reviewedby, $date)
  {
    try  
    { 
      $stmt = $pdo->prepare(

        'INSERT INTO review (itemid, rating, comments, reviewedby, reviewdate)
        VALUES (:revieweditemid, :rating, :comments, :reviewedby, :reviewdate)'
        ); 

      $stmt->bindValue(':itemid', $itemid);
      $stmt->bindValue(':rating', $rating);
      $stmt->bindValue(':comments', $comments);
      $stmt->bindValue(':reviewedby', $reviewedby);
      $stmt->bindValue(':reviewdate', $date);

      $stmt->execute();

    }
    catch (PDOException $e) 
    { 
      echo $e->getMessage(); 
    }
    echo "!!!";
  }
  */ ?>

  <br/>
  
   <!-- LIST OF REVIEWS -->
  <?php foreach ($reviewsByItem as $review) : ?>

    <div class="panel panel-default">
      <div class="panel-body">
       <li class="media">
        <a class="pull-left" href="#">
          <img class="media-object" src="<?php echo $this->basePath('img/userIcon.png') ?>" alt="...">
        </a>
        <div class="media-body">
          <h4 class="media-heading">Reviewed by: <?php echo $this->escapeHtml($review->getFirstName()); ?></h4>

          <!-- PRINT OUT THUMBS UP RATING -->
          <?php 
          $up = $this->escapeHtml($review->getRating());
          $down = 5 - $up;

          for ($i=1; $i<=$up; $i++) {
            echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
          }


          for ($i=1; $i<=$down; $i++) {
            echo '<i class="fa fa-thumbs-down fa-2x" style="color: #d9534f;"></i>';
          }
          ?>
          <br/>
          <!-- END PRINT OUT THUMBS UP RATING -->

          <?php echo $this->escapeHtml($review->getReviewdate());?>
          <?php echo $this->escapeHtml($review->getComments());?>

        </div>
      </li>



    </div>
  </div>


<?php endforeach; ?>
<!-- END LIST OF REVIEWS -->
 
</div>


