	<div class="jumbotron">

<fs>


		<h1><a class="btn btn-primary btn-lg pull-left" href="./../"><i
			class="fa fa-arrow-left fa-2x"></i><?php echo $this->translate(' BACK')?></a>
			<?php
				echo '&nbsp';
				$title = $this->escapeHtml ( $stadium->title );
				$this->headTitle ( $title );
			?>
			<?php echo $this->escapeHtml($title); ?></h1>
			<br/>


			<!-- ITEM INFORMATION -->
			<div id="itemInfo" class="panel panel-default">
				<!-- <h2>Information:</h2> -->
				<img class="itemLogo" align="left"
				src="<?php echo $this->basePath('img/stadium/'.$stadium->id.'.png') ?>"
				alt="<?php echo $this->escapeHtml($stadium->title);?>" />

				<?php echo $this->escapeHtml($stadium->info);?>
			</div>
			<!-- END ITEM INFORMATION -->



			<div class="row">
				<div id="back1" class="col-lg-5 col-md-12 col-sm-12 col-xs-12">
					<!-- STADIUM CONTACT DETAILS -->
					<div id="itemInfo" class="panel panel-default">
						<h2>Contact Details:</h2>

						<?php echo "<strong>Address:</strong><br/>".$this->escapeHtml($stadium->address);?>
						<br />
						<?php echo "<strong>Phone:</strong><br/>".$this->escapeHtml($stadium->telephone);?>
						<br />

						<?php	
						$email = $this->escapeHtml ( $stadium->email );
						
						if ($email != '') {
							echo "<strong>Email:</strong><br/>".$email . '<br/>';
						}
						
						?>  
						<?php echo "<strong>Web-site:</strong><br/>".$this->escapeHtml($stadium->website);?>
					</div>
					<!-- END STADIUM CONTACT DETAILS -->
				</div>
				<div id="back1" class="col-lg-7 col-md-12 col-sm-12 col-xs-12">
					<!-- GOOGLE MAPS -->
					<?php $address = $this->escapeHtml($stadium->address); ?>

					<iframe id="gm" frameborder="0" scrolling="no" marginheight="0"
					marginwidth="0"
					src="https://maps.google.com/maps?q=<?php echo $this->escapeHtml($title).$this->escapeHtml($address); ?>&amp;ie=UTF8&amp;hq=&amp;
					hnear=<?php echo $this->escapeHtml($title).$this->escapeHtml($address); ?>&amp;t=m&amp;z=15&amp;output=embed"></iframe>

					<!-- END GOOGLE MAPS -->
				</div>
			</div>




	





<p>
  <h2>User reviews:</h2>
  <!-- Button trigger modal REVIEW -->
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modalReview<?php echo $this->escapeHtml($stadium->id);?>">
    <i class="fa fa-pencil fa-2x"></i> Post Review
  </button>
</p>  
  <!-- Modal REVIEW -->
  <div class="modal fade bs-example-modal-lg" id="modalReview<?php echo $this->escapeHtml($stadium->id);?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel"><?php echo $this->escapeHtml($stadium->title);?></h4>
        </div>
        
        <?php 
        
        if ($user = $this->identity()) {
        
        	$userId = $this->escapeHtml($user->getId());
        	echo $this->partial('/review/review/add.phtml',
        			array('place' => $stadium, 'form' => $form, 'category' => 6, 'userId' =>$userId));
        	
        } else {
        	//throw new Exception('Not logged in');
        	echo '<div class="loginRequest"><b>Please Login</b> <br>Login form must be here!</div>';
        }
        ?>
        
      </div>
    </div>
  </div>
  <!-- END Modal REVIEW -->

  <br/>
  
   <!-- LIST OF REVIEWS -->
  <?php foreach ($reviewsByItem as $review) : ?>

    <div class="panel panel-default">
      <div class="panel-body">
       <li class="media">
        <a class="pull-left" href="#">
          <img class="media-object" src="<?php echo $this->basePath('img/userIcon.png') ?>" alt="...">
        </a>
        <div class="media-body">
          <h4 class="media-heading">Reviewed by: <?php echo $this->escapeHtml($review->getFirstName()); ?></h4>

          <!-- PRINT OUT THUMBS UP RATING -->
          <?php 
          $up = $this->escapeHtml($review->getRating());
          $down = 5 - $up;

          for ($i=1; $i<=$up; $i++) {
            echo '<i class="fa fa-thumbs-up fa-2x" style="color: #70d900;"></i>';
          }


          for ($i=1; $i<=$down; $i++) {
            echo '<i class="fa fa-thumbs-down fa-2x" style="color: #d9534f;"></i>';
          }
          ?>
          <br/>
          <!-- END PRINT OUT THUMBS UP RATING -->

          <?php echo $this->escapeHtml($review->getReviewdate());?>
          <?php echo $this->escapeHtml($review->getComments());?>

        </div>
      </li>



    </div>
  </div>


<?php endforeach; ?>
<!-- END LIST OF REVIEWS -->
 
 </fs>
</div>


