<?php

include 'inc/adminNav.inc';

$title = 'Admin Page';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>



<div class="row">
				<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
					<div id="itemInfo" class="panel panel-default">
						<h3>New Reviews: <span class="badge">1</span></h3>
						<h3>New Feedback: <span class="badge">1</span></h3>
						<h3>More.. <span class="badge">1</span></h3>
					</div>
				</div>
				<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
					<div id="itemInfo" class="panel panel-default">
						More..
					</div>
				</div>
</div>
