<?php
$title = 'Admin Page';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Nav tabs -->
<ul class="nav nav-tabs" style="height: 40px;" role="tablist">
  <li class="active"><a href="#reviews" role="tab" data-toggle="tab">Reviews</a></li>
  <li><a href="#profile" role="tab" data-toggle="tab">Profile</a></li>
  <li><a href="#messages" role="tab" data-toggle="tab">Users</a></li>
  <li><a href="#settings" role="tab" data-toggle="tab">Statistics</a></li>
</ul>
<!-- END Nav tabs -->
<br/>
<br/>

<!-- Tab panes -->
<div class="tab-content">

<!-- TAB REVIEWS -->
  <div class="tab-pane active" id="reviews">
  
  <div class="btn-group btn-group-lg">
  <button type="button" class="btn btn-primary">New</button>
  <button type="button" class="btn btn-primary">All</button>
</div>
<br/>
<br/>

<!-- REVIEWS TABLE-->
<div class="panel panel-default">

	<table class="table">
		<tr>
			<td><strong>UserID</strong></td>
			<td><strong>Date</strong></td>
			<td><strong>Comments</strong></td>
			<td><strong>Category</strong></td>
			<td><strong>Options</strong></td>
		</tr>

<?php foreach ($reviews as $review) : ?>
		<tr>
			<td>
			<?php echo $this->escapeHtml($review->getReviewedBy()); ?>
			</td>
			<td>
			<?php echo $this->escapeHtml($review->getReviewdate()); ?>
			</td>
			<td>
			<?php echo $this->escapeHtml($review->getComments()); ?>
			</td>
			<td>
			<?php echo $this->escapeHtml($review->getCategoryId()); ?>
			</td>
			<td>
			<a href="#" onClick="#"><i class="fa fa-check-circle-o fa-2x"></i>Approve</a>
			<a href="#" onClick="#"><i class="fa fa-times-circle-o fa-2x"></i>Cancel</a>
			<a href="#" onClick="#"><i class="fa fa-trash-o fa-2x"></i>Delete</a>		
			</td>
		</tr>
<?php endforeach; ?>
	</table>
</div>
<!-- END REVIEWS TABLE-->
</div>
<!-- END TAB REVIEWS -->  
  
  
  
  
  <div class="tab-pane" id="profile">.2..</div>
  <div class="tab-pane" id="messages">.3..</div>
  <div class="tab-pane" id="settings">.4..</div>
</div>