<?php
$title = 'Admin Page';
$this->headTitle ( $title );
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<!-- Nav tabs -->
<ul class="nav nav-tabs" style="height: 40px;" role="tablist">
  <li ><a href="../../" role="tab" data-toggle="tab">Reviews</a></li>
  <li class="active"><a href="#" role="tab" data-toggle="tab">Queries</a></li>
  <li><a href="#messages" role="tab" data-toggle="tab">Users</a></li>
  <li><a href="#settings" role="tab" data-toggle="tab">Statistics</a></li>
</ul>
<!-- END Nav tabs -->
<br/>
<br/>

<!-- Tab panes -->
<div class="tab-content">

<!-- TAB REVIEWS -->
  <div class="tab-pane active" id="queries">
  
  <div class="btn-group btn-group-lg">
  <button type="button" class="btn btn-primary">New</button>
  <button type="button" class="btn btn-primary">All</button>
</div>
<br/>
<br/>

<!-- REVIEWS TABLE-->
<div class="panel panel-default">

	<table class="table">
		<tr>
			<td><strong>Name</strong></td>
			<td><strong>Email</strong></td>
			<td><strong>Comments</strong></td>
		</tr>

<?php foreach ($queries as $query) : ?>
		<tr>
			<td>
			<?php echo $this->escapeHtml($query->getName()); ?>
			</td>
			<td>
			<?php echo $this->escapeHtml($query->getEmail()); ?>
			</td>
			<td>
			<?php echo $this->escapeHtml($query->getComments()); ?>
			</td>
			<td>
			<a href="#" onClick="#"><i class="fa fa-check-circle-o fa-2x"></i>Approve</a>
			<a href="#" onClick="#"><i class="fa fa-times-circle-o fa-2x"></i>Cancel</a>
			<a href="#" onClick="#"><i class="fa fa-trash-o fa-2x"></i>Delete</a>		
			</td>
		</tr>
<?php endforeach; ?>
	</table>
</div>
<!-- END REVIEWS TABLE-->
</div>
<!-- END TAB REVIEWS -->  
  
  
  
  
  <div class="tab-pane" id="profile">.2..</div>
  <div class="tab-pane" id="messages">.3..</div>
  <div class="tab-pane" id="settings">.4..</div>
</div>