<?php echo $this->doctype(); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle($this->translate('RoveAndRave'))->setSeparator(' - ')->setAutoEscape(false) ?>

  <?php echo $this->headMeta()
  ->appendName('viewport', 'width=device-width, initial-scale=1.0')
  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
  ->prependStylesheet($this->basePath() . '/css/style.css')
  ->prependStylesheet($this->basePath() . '/css/CsnUser.css')
  ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

  <!-- Scripts -->
  <?php echo $this->headScript()
  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
  ->prependFile($this->basePath() . '/js/jquery.min.js')
  ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
  ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
  ; ?>


  <!-- MOBILE APP SUPPORT -->

    <!-- iOS mobile app support -->
    <script type="text/javascript">$(document).ready(function() {$('#jclock').jclock();});</script>
    <!-- Define the icon for mobile sevice home screen -->
    <link rel="apple-touch-icon" href="./img/iconApp.png"/>
    <!-- Splash screen -->
    <link rel="apple-touch-startup-image" href="./img/iconApp.png" />
    <!-- Make the Application Full Screen -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <!-- Status bar style -->
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <!-- Setting the Viewport -->
    <meta name="viewport" content = "width = device-width, initial-scale = 2.3, user-scalable = no" />
    <meta name="viewport" content = "width = device-width, initial-scale = 2.3, minimum-scale = 1, maximum-scale = 5" />
    <!-- END iOS mobile app support -->

    <!-- Android mobile app support -->
    <meta name="viewport" content="width=device-width">
    <meta name="mobile-web-app-capable" content="yes">
    <!-- Define the icon for mobile sevice home screen -->
    <link rel="icon" sizes="196x196" href="./img/iconApp.png">
    <!-- END Android mobile app support -->

  <!-- END MOBILE APP SUPPORT -->

</head>
<body>



  <!-- CAROUSEL -->
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
  <!--
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
-->

<!-- Wrapper for slides -->
<div class="carousel-inner">
  <div class="item active">
    <img src="http://rnr2.roveandrave.com.au/public/img/adv/rnr2.png" alt="...">
  </div>

  <div class="item">
    <img src="http://rnr2.roveandrave.com.au/public/img/adv/adv2.png" alt="...">
    <div class="carousel-caption">
     <a id="advBtn" class="btn btn-info pull-right" href="about" target="_blank" ><?php echo $this->translate('More Info')?> &raquo;</a>
   </div>
 </div>

</div>



<!-- Controls -->
<div id="carouselControls">
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>
<!-- END CAROUSEL -->









<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>



      <!-- SOCIAL MEDIA BUTTONS -->
      <div id="socMedBtn" class="btn-group pull-right">
        <a class="btn btn-primary pull-left" href="https://www.facebook.com/endeavourfoundation" target="_blank" ><i class="fa fa-facebook-square fa-3x"></i></a>
        <a class="btn btn-danger pull-right" href="https://www.youtube.com/user/EndeavourFoundation" target="_blank" ><i class="fa fa-youtube-square fa-3x"></i></a>
      </div>
      <!-- END SOCIAL MEDIA BUTTONS -->

    </div>


    <div class="collapse navbar-collapse pull-right">
      <!-- MENU BAR -->
      <?php echo html_entity_decode($this->navigation("navigation")->menu()->setUlClass("nav navbar-nav")); ?>
      <!-- END MENU BAR -->



      <!-- SOCIAL MEDIA BUTTONS -->
 <!--     <div class="btn-group pull-right">
        <a class="btn btn-primary pull-left" href="https://www.facebook.com/endeavourfoundation" target="_blank" ><i class="fa fa-facebook-square fa-3x"></i></a>
        <a class="btn btn-danger pull-right" href="https://www.youtube.com/user/EndeavourFoundation" target="_blank" ><i class="fa fa-youtube-square fa-3x"></i></a>
      </div>
      <!-- END SOCIAL MEDIA BUTTONS -->





      <!-- SETTINGS BAR -->
<!--      <ul class="nav navbar-nav navbar-right">
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-search-minus fa-2x"></i></a></li>
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-circle-o fa-2x"></i></a></li>
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-search-plus fa-2x"></i></a></li>
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-volume-up fa-2x"></i></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">COLOUR <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li style="color: red; background-color:yellow;"><a href="#">Dropdown link</a></li>
            <li style="color: blue;"><a href="#">Dropdown link</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      <!-- END SETTINGS BAR -->

    </div><!--/.nav-collapse -->
  </div>
</nav>







<!-- LEFT SETTINGS BAR -->
<div class="col-md-3" id="leftCol">

  <ul class="nav nav-stacked" id="sidebar">
    <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-search-minus fa-3x"></i></a></li>
    <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-circle-o fa-3x"></i></a></li>
    <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-search-plus fa-3x"></i></a></li>
    <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-volume-up fa-3x"></i></a></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">COLOUR <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li style="color: red; background-color:yellow;"><a href="#">Dropdown link</a></li>
        <li style="color: blue;"><a href="#">Dropdown link</a></li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a></li>
      </ul>

    </div>

    <!-- END LEFT SETTINGS BAR --> 








    <div class="container">

      <?php echo $this->content; ?>
      <!-- <hr> -->
      <footer>


        <center>

          <div id="sponsorDiv">
            <a href="http://www.ndis.gov.au/" target="_blank"><img id="ndis" class="sponsorImg" src="http://roveandrave.com.au/images/sponsor/ndis.png" alt="National Disability Insurance Scheme"/></a>
            <a href="http://www.endeavour.com.au/" target="_blank"><img id="endeavour" class="sponsorImg" src="http://roveandrave.com.au/images/sponsor/endeavour.jpg" alt="Endeavour Foundation"/></a>
            <a href="https://www.qut.edu.au/" target="_blank"><img id="qutLogo" class="sponsorImg" src="http://roveandrave.com.au/images/sponsor/qutLogo.jpg" alt="Queensland University of Technology"/></a>
          </div>

          &copy; <?php echo date('Y') ?>  Rove And Rave by ENDEAVOUR. <?php echo $this->translate('All rights reserved.') ?>

        </center>
      </footer>
    </div> <!-- /container -->

    <!-- SET CAROUSEL TRANSITION SPEED TO 20 SEC -->
    <script src="../../dist/js/bootstrap.min.js"></script>  
    <script>
    $('.carousel').carousel({
     interval: 20000
   });
    </script>
    <!-- END SET CAROUSEL TRANSITION SPEED TO 20 SEC -->


    <?php echo $this->inlineScript() ?>
  </body>
  </html>
