<h2>About Rove and Rave </h2>
<p>In late 2012 Endeavour Foundation entered a team into the inaugural Social Innovation Challenge, with the team successfully winning the Challenge. The team developed the concept of roveandrave, a website and mobile application that met the wants and needs of people with a disability based on the criteria of the Challenge, as follows:</p>
<p>Employs or supports self-employment by people with a disability</p>
<p>Is an aid to their daily living</p>
<p>Supports the social and economic participation of people with a disability in other ways</p>
<p>People with a disability report that often their needs are not considered in social and entertainment spaces, other than providing wheel chair accessible entrances, exits and toilets. There are multiple considerations for people with a disability when catering to their needs and ensuring that they have the same access to social and entertainment facilities as all people. Roveandrave in concept can be a catalyst to changing how business caters to the needs of people with a disability.</p>
<h2>About Endeavour Foundation</h2>
<p>Endeavour Foundation is an independent not-for-profit organisation supporting people with a disability in more than 4,000 placements from more than 230 locations in Queensland, New South Wales and Victoria.</p>
<p>We are one of Queensland’s oldest charities, founded in 1951 by a group of parents who refused to accept their children with an intellectual disability couldn’t be educated. Forming a makeshift school on a verandah in Coorparoo, Brisbane, these courageous women taught their children basic numeracy, literacy and life skills, and advocated for change.</p>
<p>Through their early efforts, the organisation has grown into one of the leading disability support services in the country.</p>
<p>
	Read about
	<a target="_blank" href="https://www.endeavour.com.au/Our-Endeavour-Foundation/Our-History">
		<font color="#ffffff">Endeavour Foundation’s history.</font>
	</a>
</p>
<p>
	<strong>Our goal is to support people with a disability to have the opportunities and choices of an ordinary life.</strong>
	<br>
	<br>
	We do this in a number of ways:
</p>
<ul>
	<li>
		<a target="_blank" href="https://www.endeavour.com.au/Disability-services/">
			<font color="#ffffff">Disability Services</font>
		</a>
	</li>
	<li>
		<a target="_blank" href="https://www.endeavour.com.au/Business-solutions/">
			<font color="#ffffff">Business Solutions</font>
		</a>
	</li>
	<li>
		<a target="_blank" href="https://www.endeavour.com.au/Shop-with-us">
			<font color="#ffffff">Shops</font>
		</a>
	</li>
	<li>
		<a target="_blank" href="https://www.endeavour.com.au/Our-Endeavour-Foundation/Advocacy-NDIS">
			<font color="#ffffff">Advocacy</font>
		</a>
	</li>
	<li>
		<a target="_blank" href="https://www.endeavour.com.au/Ways-to-support-us/Participate-in-events">
			<font color="#ffffff">Events</font>
		</a>
	</li>
</ul>
<h2>Funding</h2>
<p>
	Approximately 60 per cent of our funding comes from state and federal governments. The remaining 40 per cent is raised through
	<a target="_blank" href="https://www.endeavour.com.au/Ways-to-support-us/Participate-in-events">
		<font color="#ffffff">events</font>
	</a>
	,
	<a target="_blank" href="https://www.endeavour.com.au/Ways-to-support-us/Purchase-lottery-tickets">
		<font color="#ffffff">lotteries</font>
	</a>
	,
	<a target="_blank" href="https://www.endeavour.com.au/Ways-to-support-us/Fundraise">
		<font color="#ffffff">fundraising activities</font>
	</a>
	,
	<a target="_blank" href="https://www.endeavour.com.au/Ways-to-support-us/Donate">
		<font color="#ffffff">donations</font>
	</a>
	and our own
	<a target="_blank" href="https://www.endeavour.com.au/Business-Solutions">
		<font color="#ffffff">Business Solutions</font>
	</a>
	.
</p>