<div class="jumbotron">

	<fs>


			<!-- CONTACT DETAILS -->		
			<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
				<strong>Australia Phone (Free):</strong> 1800 63 40 40<br/>
				<strong>Australia Fax:</strong> 1800 62 40 09<br/>
				<strong>New Zealand Phone:</strong> 0800 44 22 35<br/>
				<strong>International Phone:</strong> +617 3908 7295<br/>
				<strong>International Fax:</strong> +617 3908 7158<br/>
				<strong>Email:</strong> supporterresponse@endeavour.com.au<br/>

				<h3>Customer Service Centre</h3>
				Monday - Friday 8am - 8pm<br/>
				Saturday 9am - 1pm EST<br/>
				Closed public holidays.<br/>

				<h3>Endeavour Foundation Head Office Address:</h3>
				50 Southgate Avenue, Cannon Hill, QLD 4170, Australia.
				<h3>Postal Address:</h3>
				Endeavour Foundation, PO Box 3578, Tingalpa DC QLD 4173, Australia.
			</div>
			<!-- END CONTACT DETAILS -->


			<!-- CONTACT FORM -->
			<form id="question" class="form" name="question" method="post" action="/rnr2/public/user/login">
					<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
						<h2>Contact Us: </h2>

						<input class="form-control input-lg" type="text" value="" placeholder="What is your name?" name="qname">
						<input class="form-control input-lg" type="text" value="" placeholder="What is your email?" name="qemail">
						<textarea class="form-control" style="height:200px; font-size:14pt;" placeholder="Type your question here..." name="qemail"></textarea>
						<button class="btn btn-success btn-lg" type="button">
							<i class="fa fa-check fa-2x"></i>
							SUBMIT
						</button>
					</div>
			</form>

			<!-- END CONTACT FORM -->



		</div>
	</fs>
</div>