<div class="jumbotron">

<fs>

<h2> Frequently Asked Questions: </h2>

<p>
<strong> Q. Who is the main audiance of this site? </strong>
<br>
A: We are focusing on ID person.
</p>
<p>
	<strong> Q. Will this site be available for 24x7? </strong>
	<br>
	A: Yes
</p>
<p>
	<strong> Q. RED or pink wallpapers? </strong>
	<br>
	A. Ok we will add more color.
</p>

</fs>

<a class="btn btn-primary btn-lg pull-left" href="./contact">
<i class="fa fa-question-circle fa-2x"></i>
ASK QUESTION
</a>

</div>