<div class="row">


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #ed7602 0px, #ed7602 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Restaurants') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/1.png') ?>" alt="Restaurants"/></a></p>
            </div>
        </div>
    </div>


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #9db5ff 0px, #9db5ff 100%);"> 
                <h3 class="panel-title-home"><?php echo $this->translate('Hotels') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/2.png') ?>" alt="Stadiums"/></a></p>
            </div>
        </div>
    </div>


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #94d494 0px, #94d494 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Parks') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/3.png') ?>" alt="Albums"/></a></p>
            </div>
        </div>
    </div>


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #31cae5 0px, #31cae5 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Libraries') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/4.png') ?>" alt="Albums"/></a></p>
            </div>
        </div>
    </div>




    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #de89e2 0px, #de89e2 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Cinemas') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/5.png') ?>" alt="Stadiums"/></a></p>
            </div>
        </div>
    </div>

        <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #b5b2b4 0px, #b5b2b4 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Stadiums') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/6.png') ?>" alt="Stadiums"/></a></p>
            </div>
        </div>
    </div>


</div>
