<div class="row">


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #f95039 0px, #f95039 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Restaurants') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/1.png') ?>" alt="Restaurants"/></a></p>
            </div>
        </div>
    </div>


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #78b9bd 0px, #78b9bd 100%);"> 
                <h3 class="panel-title-home"><?php echo $this->translate('Hotels') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/2.png') ?>" alt="Stadiums"/></a></p>
            </div>
        </div>
    </div>


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #01ba64 0px, #01ba64 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Parks') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/3.png') ?>" alt="Albums"/></a></p>
            </div>
        </div>
    </div>


    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #f7b060 0px, #f7b060 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Libraries') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/4.png') ?>" alt="Albums"/></a></p>
            </div>
        </div>
    </div>




    <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #3ab4f0 0px, #3ab4f0 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Cinemas') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/5.png') ?>" alt="Stadiums"/></a></p>
            </div>
        </div>
    </div>

        <div class="col-md-3 col-xs-6">
        <div class="panel panel-default">
            <div class="panel-heading" style="background-image: linear-gradient(to bottom, #a70050 0px, #a70050 100%);">
                <h3 class="panel-title-home"><?php echo $this->translate('Stadiums') ?></h3>
            </div>
            <div class="panel-body">
                 <p><a href="<?php echo $this->url('stadium') ?>"><img class="imageBox" src="<?php echo $this->basePath('img/6.png') ?>" alt="Stadiums"/></a></p>
            </div>
        </div>
    </div>


</div>
